services:
  auth-app:
    build: .
    image: auth-service:${BACKEND_VERSION:-latest}
    container_name: auth-service-container
    ports:
      - "8084:8080"
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-db:5432/auth
      - SPRING_PROFILES_ACTIVE=prod
      - OUTPUT=file
      - JAVA_OPTS=-Xmx384m
    volumes:
      - /var/log/auth-service:/app/logs
      - /home/backend/auth-service/jwt:/app/jwt
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: docker_shared-network
